LOGO_BEGIN_X = 3
LOGO_BEGIN_Y = 2
LOGO_WIDTH = 54
LOGO_HEIGHT = 24

BUTTONS_BEGIN_X = 30
BUTTONS_BEGIN_Y = 16
BUTTONS_WIDTH = 11
BUTTONS_HEIGHT = 7

TEXTS_BEGIN_X = 1
TEXTS_BEGIN_Y = 27
TEXTS_WIDTH = 59
TEXTS_HEIGHT = 9

BUTTON_START = 0
BUTTON_OPTIONS = 1
BUTTON_HIGH_SCORES = 2
BUTTON_QUIT = 3
