TITLE_VIEW_LOGO_BEGIN_X = 3
TITLE_VIEW_LOGO_BEGIN_Y = 2
TITLE_VIEW_LOGO_WIDTH = 54
TITLE_VIEW_LOGO_HEIGHT = 24

TITLE_VIEW_BUTTONS_BEGIN_X = 30
TITLE_VIEW_BUTTONS_BEGIN_Y = 16
TITLE_VIEW_BUTTONS_WIDTH = 11
TITLE_VIEW_BUTTONS_HEIGHT = 7

TITLE_VIEW_TEXTS_BEGIN_X = 1
TITLE_VIEW_TEXTS_BEGIN_Y = 27
TITLE_VIEW_TEXTS_WIDTH = 59
TITLE_VIEW_TEXTS_HEIGHT = 9
